### ISSUE TITLE
Selection of warning level for shipping via pushover etc.

### ISSUE THREAD

**Issue by Draexl** [jack-blackson/ioBroker.meteoalarm#157]
It would be great if you had the option to set which warning level should be sent for the shipping methods via Telegram, Pushover etc.
I would prefer if I could only get 3/4 and 4/4. Everything below is of little interest to me

**Comment by jack-blackson** [comment]
This is a good idea. I was thinking about that already before. But I think it would make sense to have this filter not just for the notifications, but for the instance in general - so that it also has an effect on the HTML widget and so on. If somebody wants different data for notifications and widgets, they can have separate instances.

**Comment by Draexl** [comment]
Good idea. Although I would prefer an instance with two choices. But if it's easier to implement otherwise, your idea is welcome 😄

**Comment by jack-blackson** [comment]
Hey!

I have a new version available with the changes you mentioned here. You can install it via this link: https://github.com/jack-blackson/ioBroker.meteoalarm/tarball/v2.3.3

There is now a setup in the second tab to define what alarm levels you want in general - so for the widget, or for the JSON table. In the 4th tab, you can do the same setup for the notifications - and also define the types you want the notifications for.

Please let me know if this works out for you.

**Comment by Draexl** [comment]
Thanks, I checked :-)
