### ISSUE TITLE
Geocode-Datei von meteoalarm.org updated for Switzerland

### ISSUE THREAD

**Issue by VKTML** [jack-blackson/ioBroker.meteoalarm#93]
Hello, 
It looks like the Geocode-File for Switzerland has been updated and it's working again.
If so, could you add Switzerland again?
Thanks a lot for checking.

Cheers

<img width="1680" alt="Screenshot 2021-10-04 at 21 50 27" src="https://user-images.githubusercontent.com/29674720/135915182-4baba74d-f825-4ffe-8d7e-e8ee0240c797.png">

**Comment by git828** [comment]
+1 Thank You

**Comment by jack-blackson** [comment]
Hey!

Why do you think it was updated? Because the alarms show up on the website? Unfortunately, the file is still incorrect. Let me explain the problem a little bit in detail.

All regions have a region code, which helps me to find the corresponding alarms in the alarm feed. To be able to show the region names in the setup, and then in the background save the corresponding region code, I use the geocode.json file from here: https://edrop.zamg.ac.at/owncloud/index.php/s/FegwJnoC3XiesnE. This is the folder from the Reuse-are from the meteoalarm.org website.

This is how the file looks like for an Austrian region e.g.
![grafik](https://user-images.githubusercontent.com/13975634/136071779-a8b30d97-e16e-4a79-8dd9-230678515a99.png)

Unfortunately, for Switzerland, Bulgaria and Portugal, the file seems to be wrong, because all regions look like that:
![grafik](https://user-images.githubusercontent.com/13975634/136071897-abd3644e-8a60-4675-a08f-3074007c0ec3.png)
So instead of having the region name in the attribut "name", it shows "Switzerland" for all of them.

I reported this to zamg already two times, and they said they will inform the IT support, but unfortunately they haven't fixed it yet. I don't see a possibility for now how to get the conversion from this code to the corresponding name. It works perfect for all other european countries in this file.

**Comment by jack-blackson** [comment]
Hello!

I have good news. It is now possible to also receive the alarms for Switzerland. To install the update, please update the adapter with this link: https://github.com/jack-blackson/ioBroker.meteoalarm/tarball/v2.1.0

I would be happy if you can give me some feedback if it works out fine.

**Comment by VKTML** [comment]
Great to hear!
Just installed the update. 
All working so far, but can't give final feedback, as there are currently no warnings.
I'll try to keep an eye on new alerts to check if they are received in the adapter.
Thanks a lot for your work!

**Comment by git828** [comment]
Cool !!
Thanks to you Jack and 
Thanks to R. Kaltenberger who updated the data from MeteoSchweiz.

**Comment by git828** [comment]
Today we have a wind warning
![Screenshot 2022-02-06 163335](https://user-images.githubusercontent.com/58549168/152688413-7f0e3eea-c2fd-4258-9ecb-5b28e8916bd3.png)
But object shows
![Screenshot 2022-02-06 163312](https://user-images.githubusercontent.com/58549168/152688419-6a8fa2e7-7394-49eb-bcf3-c08a513e7992.png)

**Comment by jack-blackson** [comment]
Is it still not showing up? I just activated this region, and can see alarms: 
<img width="476" alt="grafik" src="https://user-images.githubusercontent.com/13975634/152696547-b1341e76-cf17-49ff-bd13-279a05c5f4ea.png">
Need to check why it shows the same one twice.

**Comment by git828** [comment]
thanks for checking. I am going to reinstall adapter.

**Comment by git828** [comment]
It is working now,
